language: python

python:
  - "3.7"

sudo: required

install:
  - ./setup.sh travis
  - source env/bin/activate

script: make

deploy:
  provider: releases
  api_key: "GITHUB_OAUTH_TOKEN"
  file: "FILE_TO_UPLOAD"
  skip_cleanup: true
  overwrite: true
