language: python
dist: disco

python:
  - "3.7"

sudo: required

install:
  - ./setup.sh travis
  - source env/bin/activate

jobs:
  include:
    - if: branch = master
    # - stage: "Test"
    #   name: "Unit Tests"
    #   script: skip
    - stage: "Release"
      name: "GitHub Release"
      before_deploy:
        - script: make
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: $FILE_TO_UPLOAD
        skip_cleanup: true
        overwrite: true
