# Hue Documentation to get IP and Create Username for their API:
#    https://developers.meethue.com/develop/get-started-2/

# Hue Bridge user and ip address for qhue
bridge:
    user: UnnyZonejfw0Su1AJlQ1PmNGFh7mBHaRxc73cZH0
    ip: 192.168.1.114



# Hue Documentation to get list of all lights:
#    https://developers.meethue.com/develop/hue-api/lights-api/

# Lights to change colors. Match the integer of the lights from the
# above step to create a list of lights you would like to change colors
lights:
    - 1 # Hue Color Lamp 1
    - 4 # Hue Play 1
    - 5 # Hue Play 2